spring:
  cloud:
    gateway:
      routes:
        # User Status Check (Requires Authentication)
        - id: user_status_check
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/users/status/check
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        # User Get, Update and Delete (Requires Authentication)
        - id: user_get_update_delete
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/users/**
            - Method=GET,PUT,DELETE
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        # User Sign Up (No Authentication)
        - id: user_sign_up
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/users/sign-up
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        # User Sign In (No Authentication)
        - id: user_sign_in
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/users/sign-in
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}