server:
  port: ${PORT:0}

spring:
  application:
    name: album-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  pattern:
    level: %5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-