spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:user_db
    username: sa
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

token:
  expiration_time: 3600000

management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: gateway,health,mappings,beans,httpexchanges