spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

token:
  expiration_time: 3600000

management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: gateway,health,mappings,beans,httpexchanges