version: "3"
services:
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.12-management
#    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

#  zipkin:
#    image: openzipkin/zipkin
##    restart: always
#    ports:
#      - 9411:9411

  config-server:
    image: mtopgul/config-server:0.0.1-SNAPSHOT
    container_name: config-server
    restart: on-failure
    ports:
      - 8888:8888
    depends_on:
      - rabbitmq3

  discovery-service:
    image: mtopgul/discovery-service:0.0.1-SNAPSHOT
    container_name: discovery-service
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8010:8010
    depends_on:
      - config-server

  account-service:
    image: mtopgul/account-service:0.0.1-SNAPSHOT
    container_name: account-service
    restart: on-failure
    environment:
      - SERVER_PORT=9010
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 9010:9010
    depends_on:
      - config-server
      - discovery-service

  album-service:
    image: mtopgul/album-service:0.0.1-SNAPSHOT
    container_name: album-service
    restart: on-failure
    environment:
      - SERVER_PORT=9011
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 9011:9011
    depends_on:
      - config-server
      - discovery-service

  user-service:
    image: mtopgul/user-service:0.0.1-SNAPSHOT
    container_name: user-service
    restart: on-failure
    environment:
      - SERVER_PORT=9012
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 9012:9012
    depends_on:
      - config-server
      - discovery-service
      - postgres

  api-gateway:
    image: mtopgul/api-gateway:0.0.1-SNAPSHOT
    container_name: api-gateway
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8082:8082
    depends_on:
      - config-server
      - discovery-service
