server:
  port: ${PORT:0}

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'
  level:
    com:
      mtopgul:
        photoapp:
          userservice:
            service:
              AlbumServiceClient: DEBUG
              UserService: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        register-health-indicator: true
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10000ms
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
        minimum-number-of-calls: 1
        event-consumer-buffer-size: 10
    circuit-breaker-aspect-order: 1
  retry:
    retry-aspect-order: 2
    instances:
      album-service:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multipliers: 5

management:
  tracing:
    sampling:
      probability: 1

