server:
  port: ${PORT:0}

spring:
  application:
    name: user-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}_${spring.application.instance_id:${random.value}}