server:
  port: ${PORT:0}

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    com:
      mtopgul:
        photoapp:
          userservice:
            service:
              AlbumServiceClient: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        register-health-indicator: true
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10000ms
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
        minimum-number-of-calls: 1
        event-consumer-buffer-size: 10

